# Generated by Django 6.0.7 on 2026-07-18 21:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawProfile',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('jurisdiction_type', models.CharField(choices=[('federal', 'Federal'), ('state', 'State')], max_length=32)),
                ('governing_law', models.CharField(max_length=255)),
                ('regulating_body', models.CharField(max_length=255)),
                ('procurement_methods', models.JSONField(default=list)),
                ('approval_thresholds', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('procurement_officer', 'Procurement Officer'), ('admin', 'Admin')], default='procurement_officer', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(max_length=255)),
                ('budget_source', models.CharField(choices=[('TETFund', 'TETFund'), ('IGR', 'IGR'), ('Government Subvention', 'Government Subvention'), ('Donor/Grant', 'Donor/Grant'), ('Alumni', 'Alumni'), ('Other', 'Other')], max_length=32)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('awarded_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('procurement_method', models.CharField(max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Advertised', 'Advertised'), ('Tendering', 'Tendering'), ('Awarded', 'Awarded'), ('Implementation', 'Implementation'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], default='Planning', max_length=32)),
                ('location', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('law_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='procurement.lawprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, choices=[('Planning', 'Planning'), ('Advertised', 'Advertised'), ('Tendering', 'Tendering'), ('Awarded', 'Awarded'), ('Implementation', 'Implementation'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], max_length=32, null=True)),
                ('new_status', models.CharField(choices=[('Planning', 'Planning'), ('Advertised', 'Advertised'), ('Tendering', 'Tendering'), ('Awarded', 'Awarded'), ('Implementation', 'Implementation'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='procurement.procurementrecord')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
    ]
