# Generated by Django 6.0.7 on 2026-07-19 20:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('procurement', '0002_recordflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('requesting_unit', 'Requesting Unit'), ('procurement_unit', 'Procurement Unit'), ('finance', 'Finance/Budget'), ('accounting_officer', 'Accounting Officer'), ('admin', 'Admin')], default='procurement_unit', max_length=32),
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('law_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_years', to='procurement.lawprofile')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('law_profile', 'label')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_approved', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_plans', to='procurement.financialyear')),
                ('law_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_plans', to='procurement.lawprofile')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('law_profile', 'financial_year')},
            },
        ),
        migrations.CreateModel(
            name='PlanLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=16)),
                ('budget_line', models.CharField(max_length=255)),
                ('proposed_method', models.CharField(blank=True, help_text="Non-binding — the requisition's binding method comes from ThresholdRule.", max_length=100)),
                ('proposed_quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('is_amendment', models.BooleanField(default=False)),
                ('amendment_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_lines_proposed', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.procurementplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_identifier', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('requested_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('budget_source', models.CharField(choices=[('TETFund', 'TETFund'), ('IGR', 'IGR'), ('Government Subvention', 'Government Subvention'), ('Donor/Grant', 'Donor/Grant'), ('Alumni', 'Alumni'), ('Other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('record_created', 'Record Created'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('funds_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('funds_confirmation_note', models.TextField(blank=True)),
                ('packaging_reviewed', models.BooleanField(default=False)),
                ('packaging_review_note', models.TextField(blank=True)),
                ('packaging_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('determined_method', models.CharField(blank=True, max_length=100)),
                ('determined_approving_authority', models.CharField(blank=True, max_length=255)),
                ('bpp_prior_review_required', models.BooleanField(default=False)),
                ('method_override', models.CharField(blank=True, max_length=100)),
                ('method_override_justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funds_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_funds_confirmed', to=settings.AUTH_USER_MODEL)),
                ('packaging_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_packaging_reviewed', to=settings.AUTH_USER_MODEL)),
                ('plan_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='procurement.planline')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='procurementrecord',
            name='requisition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record', to='procurement.requisition'),
        ),
        migrations.CreateModel(
            name='ThresholdRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procurement_method', models.CharField(max_length=100)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('approving_authority', models.CharField(max_length=255)),
                ('bpp_prior_review_required', models.BooleanField(default=False)),
                ('is_default_for_range', models.BooleanField(default=False, help_text='Exactly one active rule per overlapping value range/date should be the default (open competitive bidding).')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, help_text='Legal citation / rationale for this rule.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threshold_rules_created', to=settings.AUTH_USER_MODEL)),
                ('law_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threshold_rules', to='procurement.lawprofile')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='requisition',
            name='threshold_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='procurement.thresholdrule'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition')], max_length=40)),
                ('role_at_time', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='procurement_content_c79cb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessIdentifierSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_id_sequences', to='procurement.financialyear')),
                ('law_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_id_sequences', to='procurement.lawprofile')),
            ],
            options={
                'unique_together': {('law_profile', 'financial_year')},
            },
        ),
    ]
