# Generated by Django 6.0.7 on 2026-07-20 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rename_procurement_officer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawprofile',
            name='default_minimum_bidding_days',
            field=models.PositiveIntegerField(default=14, help_text='Institutional policy default: minimum number of days required between advertisement publication and bid closing. This is a configurable placeholder, NOT a verified statutory figure for any specific procurement method — the source framework gives illustrative examples (e.g. "at least 30 days for consultancy proposals") but no complete table the way it does for approval thresholds. Adjust per institution/legal review; a future increment could branch this per procurement_method once an authoritative table is available.'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published')], max_length=40),
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('eligibility_criteria', models.TextField(help_text='Who may bid: registration, category, experience requirements.')),
                ('scope_and_specifications', models.TextField(help_text='Technical specifications / scope of work / terms of reference.')),
                ('evaluation_criteria', models.TextField(help_text='Narrative evaluation methodology.')),
                ('evaluation_weights', models.JSONField(blank=True, default=dict, help_text='Optional structured weights, e.g. {"technical": 70, "financial": 30}. Informational only — automated scoring is a future evaluation phase, not built yet.')),
                ('bid_security_required', models.BooleanField(default=False)),
                ('bid_security_type', models.CharField(blank=True, help_text='e.g. Bank guarantee, insurance bond.', max_length=100)),
                ('bid_security_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitations_approved', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitations_prepared', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='procurement.procurementrecord')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('record', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channels', models.JSONField(default=list, help_text='List of channel codes — see Advertisement.CHANNEL_CHOICES.')),
                ('publication_proof', models.TextField(help_text='Reference/description of proof of publication (newspaper name+date, URL, notice-board photo reference, etc).')),
                ('closing_date', models.DateField(help_text='Bid/proposal submission deadline.')),
                ('minimum_bidding_days_applied', models.PositiveIntegerField(help_text='Snapshot of the institutional minimum-bidding-period policy in effect at publish time (see LawProfile.default_minimum_bidding_days) — kept even if the policy default later changes, so historical records stay explainable.')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisements_published', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advertisement', to='procurement.solicitation')),
            ],
        ),
    ]
