# Generated by Django 6.0.7 on 2026-07-21 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_alter_auditevent_action_prequalificationapplicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published'), ('clarification_answered', 'Clarification Answered'), ('prequalification_recorded', 'Prequalification Applicant Recorded'), ('prequalification_reviewed', 'Prequalification Applicant Reviewed'), ('bid_recorded', 'Bid Recorded'), ('award_decided', 'Award Decided')], max_length=40),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_registration_no', models.CharField(blank=True, max_length=100)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_responsive', models.BooleanField(default=True, help_text="Whether this bid meets the solicitation's eligibility/technical requirements. A non-responsive bid is still recorded, not omitted — an honest record of what was actually received — but cannot be selected as the winning bid.")),
                ('note', models.TextField(blank=True, help_text='e.g. reason for non-responsiveness.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids_recorded', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='procurement.solicitation')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_note', models.TextField(help_text='Award justification — public once decided.')),
                ('bpp_no_objection_reference', models.CharField(blank=True, max_length=100)),
                ('bpp_no_objection_date', models.DateField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards_decided', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='award', to='procurement.solicitation')),
                ('winning_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.bid')),
            ],
        ),
    ]
