# Generated by Django 6.0.7 on 2026-07-21 05:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_auditevent_action_bid_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published'), ('clarification_answered', 'Clarification Answered'), ('prequalification_recorded', 'Prequalification Applicant Recorded'), ('prequalification_reviewed', 'Prequalification Applicant Reviewed'), ('bid_recorded', 'Bid Recorded'), ('award_decided', 'Award Decided'), ('complaint_resolved', 'Complaint Resolved')], max_length=40),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_contact', models.CharField(help_text='Email or phone — never shown publicly.', max_length=255)),
                ('description', models.TextField(help_text='Staff-only, even once resolved — see class docstring.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('resolution_note', models.TextField(blank=True, help_text='Public once resolved.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='procurement.procurementrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
    ]
