# Generated by Django 6.0.7 on 2026-07-21 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_alter_auditevent_action_contractcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published'), ('clarification_answered', 'Clarification Answered'), ('prequalification_recorded', 'Prequalification Applicant Recorded'), ('prequalification_reviewed', 'Prequalification Applicant Reviewed'), ('bid_recorded', 'Bid Recorded'), ('award_decided', 'Award Decided'), ('complaint_resolved', 'Complaint Resolved'), ('contract_signed', 'Contract Signed'), ('milestone_added', 'Milestone Added'), ('milestone_completed', 'Milestone Completed'), ('contract_completed', 'Contract Completed'), ('performance_guarantee_recorded', 'Performance Guarantee Recorded')], max_length=40),
        ),
        migrations.CreateModel(
            name='PerformanceGuarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guarantee_type', models.CharField(help_text='e.g. Bank guarantee, insurance bond, cash deposit.', max_length=100)),
                ('issuing_institution', models.CharField(help_text='Staff-only — see public disclosure notes.', max_length=255)),
                ('reference_number', models.CharField(help_text='Staff-only — see public disclosure notes.', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('expiry_date', models.DateField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='performance_guarantee', to='procurement.contract')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_guarantees_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
