# Generated by Django 6.0.7 on 2026-07-21 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_auditevent_action_performanceguarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published'), ('clarification_answered', 'Clarification Answered'), ('prequalification_recorded', 'Prequalification Applicant Recorded'), ('prequalification_reviewed', 'Prequalification Applicant Reviewed'), ('bid_recorded', 'Bid Recorded'), ('award_decided', 'Award Decided'), ('complaint_resolved', 'Complaint Resolved'), ('contract_signed', 'Contract Signed'), ('milestone_added', 'Milestone Added'), ('milestone_completed', 'Milestone Completed'), ('contract_completed', 'Contract Completed'), ('performance_guarantee_recorded', 'Performance Guarantee Recorded'), ('invoice_submitted', 'Invoice Submitted'), ('invoice_reviewed', 'Invoice Reviewed'), ('payment_recorded', 'Payment Recorded')], max_length=40),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('submitted_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.contract')),
                ('milestone', models.ForeignKey(blank=True, help_text='Optional — the completed milestone this invoice corresponds to, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.milestone')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_date', models.DateField()),
                ('payment_reference', models.CharField(max_length=100)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='procurement.invoice')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
