# Generated by Django 6.0.7 on 2026-07-21 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_alter_auditevent_action_invoice_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published'), ('clarification_answered', 'Clarification Answered'), ('prequalification_recorded', 'Prequalification Applicant Recorded'), ('prequalification_reviewed', 'Prequalification Applicant Reviewed'), ('bid_recorded', 'Bid Recorded'), ('award_decided', 'Award Decided'), ('complaint_resolved', 'Complaint Resolved'), ('contract_signed', 'Contract Signed'), ('milestone_added', 'Milestone Added'), ('milestone_completed', 'Milestone Completed'), ('contract_completed', 'Contract Completed'), ('performance_guarantee_recorded', 'Performance Guarantee Recorded'), ('invoice_submitted', 'Invoice Submitted'), ('invoice_reviewed', 'Invoice Reviewed'), ('payment_recorded', 'Payment Recorded'), ('tenders_board_reviewed', 'Tenders Board Reviewed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('requesting_unit', 'Requesting Unit'), ('procurement_unit', 'Procurement Unit'), ('finance', 'Finance/Budget'), ('accounting_officer', 'Accounting Officer'), ('tenders_board', 'Tenders Board'), ('admin', 'Admin')], default='procurement_unit', max_length=32),
        ),
        migrations.CreateModel(
            name='TendersBoardReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_summary', models.TextField(help_text="The board's written rationale — public once an award exists.")),
                ('quorum_present', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.bid')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders_board_reviews', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenders_board_review', to='procurement.solicitation')),
            ],
        ),
    ]
