# Generated by Django 6.0.7 on 2026-07-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_alter_auditevent_action_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawprofile',
            name='default_complaint_response_days',
            field=models.PositiveIntegerField(default=14, help_text='Institutional policy default: number of days the institution aims to resolve a complaint within, before it is flagged as overdue on both the staff and public record views. This is a configurable placeholder, NOT a verified statutory deadline — same honesty caveat as default_minimum_bidding_days above. Adjust per institution/legal review.'),
        ),
    ]
