# Generated by Django 6.0.7 on 2026-07-22 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_lawprofile_default_complaint_response_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('plan_submitted', 'Plan Submitted'), ('plan_approved', 'Plan Approved'), ('plan_rejected', 'Plan Rejected'), ('plan_line_approved', 'Plan Line Approved'), ('plan_line_rejected', 'Plan Line Rejected'), ('requisition_submitted', 'Requisition Submitted'), ('funds_confirmed', 'Funds Confirmed'), ('funds_declined', 'Funds Declined'), ('packaging_reviewed', 'Packaging Reviewed'), ('method_determined', 'Method Determined'), ('method_overridden', 'Method Overridden'), ('record_created_from_requisition', 'Record Created From Requisition'), ('solicitation_prepared', 'Solicitation Prepared'), ('solicitation_approved', 'Solicitation Approved'), ('solicitation_rejected', 'Solicitation Rejected'), ('advertisement_published', 'Advertisement Published'), ('clarification_answered', 'Clarification Answered'), ('prequalification_recorded', 'Prequalification Applicant Recorded'), ('prequalification_reviewed', 'Prequalification Applicant Reviewed'), ('bid_recorded', 'Bid Recorded'), ('award_decided', 'Award Decided'), ('complaint_resolved', 'Complaint Resolved'), ('contract_signed', 'Contract Signed'), ('milestone_added', 'Milestone Added'), ('milestone_completed', 'Milestone Completed'), ('contract_completed', 'Contract Completed'), ('performance_guarantee_recorded', 'Performance Guarantee Recorded'), ('invoice_submitted', 'Invoice Submitted'), ('invoice_reviewed', 'Invoice Reviewed'), ('payment_recorded', 'Payment Recorded'), ('tenders_board_reviewed', 'Tenders Board Reviewed'), ('record_abandoned', 'Record Abandoned')], max_length=40),
        ),
        migrations.CreateModel(
            name='Abandonment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(help_text='The status the record was in immediately before abandonment.', max_length=32)),
                ('reason', models.CharField(choices=[('need_eliminated', 'Goods/works/services no longer needed'), ('circumstances_changed', 'Change in circumstances — benefit no longer likely'), ('no_responsive_bids', 'All bids received were non-responsive'), ('budget_exceeded', 'All bids substantially exceeded the available budget'), ('integrity_concern', 'Evidence of collusion or corrupt/fraudulent practice'), ('other', 'Other (see justification)')], max_length=32)),
                ('justification', models.TextField(help_text="Public — the institution's accountable explanation.")),
                ('abandoned_at', models.DateTimeField(auto_now_add=True)),
                ('abandoned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abandonments_decided', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='abandonment', to='procurement.procurementrecord')),
            ],
        ),
    ]
