# Generated by Django 6.0.7 on 2026-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_alter_auditevent_action_mfabackupcode_totpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='totpdevice',
            name='last_used_step',
            field=models.BigIntegerField(blank=True, help_text='RFC 6238 time-step of the last successfully-verified TOTP code — rejects replay of the same code.', null=True),
        ),
        migrations.AlterField(
            model_name='totpdevice',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Reset to 0 on every fresh password-verified login attempt (see StaffLoginView.form_valid) — the actual rate limit is coupling code-guessing to the cost of a correct password guess, not a permanent ban.'),
        ),
    ]
